name: Delete AWS Sandbox Infrastructure

on:
  workflow_dispatch:
    inputs:
      confirm_delete:
        description: 'Type "DELETE" to confirm stack deletion'
        required: true

jobs:
  delete:
    runs-on: ubuntu-latest
    if: github.event.inputs.confirm_delete == 'DELETE'
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Cambia esto a tu región preferida

    - name: Delete CloudFormation Stack
      run: |
        aws cloudformation delete-stack --stack-name sandbox-stack
        echo "Stack deletion initiated. Waiting for completion..."
        aws cloudformation wait stack-delete-complete --stack-name sandbox-stack
        echo "Stack deletion completed."